export const app_users = [
        {
            name:"patient",
            alias:"patient",
            routes:[
              "check-symptoms",
              "reminders",
              "appointments",
              "prescriptions",
              "records",
              "profile",
              "chat",
              "forum",
            ]
          },
      {
        name:"health-provider",
        alias:"health provider",
        routes:[
          "dashboard",
          "appointments",
          "e-prescriptions",
          "records",
          "profile",
          "chat",
          "forum",
        ]
      },
      {
        name:"administrator",
        alias:"administrator",
        routes:[
          "dashboard",
          "users",
          "health-providers",
          "reports",
          "settings",
          "profile",
          "chat",
          "forum",
        ]
      },
      {
        name:"pharmacist",
        alias:"pharmacist",
        routes:[
          "medicines",
          "medication-history",
          "dispensation",
          "profile",
          "chat",
          "forum",
        ]
      },
      {
        name:"health-administrator",
        alias:"health administrator",
        routes:[
          "facilities",
          "staff",
          "compliance",
          "incidences",
          "profile",
          "chat",
          "forum",
        ]
      },
  ];